# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.IntegerField(default=0)),
                ('social', models.CharField(default=0, max_length=200)),
                ('genre', models.CharField(default=0, max_length=200)),
                ('location', models.CharField(default=0, max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Musicians',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.IntegerField(default=0)),
                ('social', models.CharField(default=0, max_length=200)),
                ('genre', models.CharField(default=0, max_length=200)),
                ('songs', models.CharField(default=0, max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.IntegerField(default=0)),
                ('social', models.CharField(default=0, max_length=200)),
                ('genre', models.CharField(default=0, max_length=200)),
                ('artists', models.CharField(default=0, max_length=200)),
                ('company', models.CharField(default=0, max_length=200)),
                ('engineering', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Talent_management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.IntegerField(default=0)),
                ('social', models.CharField(default=0, max_length=200)),
                ('genre', models.CharField(default=0, max_length=200)),
                ('artists', models.CharField(default=0, max_length=200)),
                ('company', models.CharField(default=0, max_length=200)),
                ('artistDevelopment', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
