# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='talent_management',
            name='artists',
        ),
        migrations.AddField(
            model_name='events',
            name='musician',
            field=models.ManyToManyField(related_name='events', to='talent.Musicians'),
        ),
        migrations.AddField(
            model_name='musicians',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musicians', to='talent.Talent_management'),
        ),
        migrations.AddField(
            model_name='musicians',
            name='production',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musicians', to='talent.Production'),
        ),
    ]
