# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_auto_20160919_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicians',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
