# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_auto_20160914_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='email',
        ),
        migrations.RemoveField(
            model_name='song',
            name='location',
        ),
        migrations.RemoveField(
            model_name='song',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='song',
            name='social',
        ),
    ]
