# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 20:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0003_musicians_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
