# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0003_auto_20160914_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
        migrations.AddField(
            model_name='song',
            name='length',
            field=models.CharField(default=0, max_length=8),
        ),
    ]
