# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0004_events_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='genre',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='social',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
