# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0004_auto_20160914_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicians',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
