# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0005_auto_20160921_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicians',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
