# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0005_auto_20160915_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicians',
            name='company',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
