# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0007_auto_20160922_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
